local utils = require("core.utils")

return {
	cmd = { "basedpyright" },
	on_new_config = function()
		-- Activate virtualenv before LSP starts
		utils.activate_venv()
	end,
	root_markers = { "pyproject.toml", "requirements.txt", ".venv", ".git" },
	settings = {
		pyright = {
			disableOrganizeImports = true,
		},
		python = {
			analysis = {
				-- ignore = { "*" },
				diagnosticSeverityOverrides = {
					-- reportMissingImports = "none",
					-- reportMissingTypeStubs = "none",
					-- reportGeneralTypeIssues = "error",
					-- reportFunctionMemberAccess = "warning",
					-- reportPrivateUsage = "warning",
					-- reportUnknownParameterType = "warning",
					-- reportUnknownArgumentType = "warning",
					-- reportUnknownLambdaType = "warning",
					-- reportUnknownVariableType = "warning",
					-- reportUnknownMemberType = "error",
					-- reportMissingTypeArgument = "warning",
					-- reportInvalidTypeVarUse = "error",
					-- reportCallInDefaultInitializer = "none",
					-- reportUnnecessaryIsInstance = "none",
					-- reportUnnecessaryCast = "none",
					-- reportUnnecessaryComparison = "none",
					-- reportAssertAlwaysTrue = "none",
					-- reportSelfClsParameterName = "none",
					-- reportImplicitStringConcatenation = "none",
					-- reportUnsupportedDunderAll = "none",
					-- reportUnusedCallResult = "none",
					-- reportUnusedCoroutine = "none",
					-- reportUninitializedInstanceVariable = "warning",
					reportArgumentType = "warning",
					reportAttributeAccessIssue = "warning",
					reportOptionalMemberAccess = "warning",
					reportOptionalOperand = "warning",
					reportReturnType = "warning",
					reportUndefinedVariable = "warning",
					reportUnboundVariable = "warning",
					reportUnusedImport = "none",
					reportUnusedVariable = "warning", -- or anything
				},
				typeCheckingMode = "standard",
				useLibraryCodeForTypes = true,
				-- reportMissingImports = false,
				-- reportMissingTypeStubs = false,
				-- reportGeneralTypeIssues = true,
				-- reportFunctionMemberAccess = true,
				-- reportPrivateUsage = true,
				-- reportUnknownParameterType = true,
				-- reportUnknownArgumentType = true,
				-- reportUnknownLambdaType = true,
				-- reportUnknownVariableType = true,
				-- reportUnknownMemberType = true,
				-- reportMissingTypeArgument = true,
				-- reportInvalidTypeVarUse = true,
				-- reportCallInDefaultInitializer = false,
				-- reportUnnecessaryIsInstance = false,
				-- reportUnnecessaryCast = false,
				-- reportUnnecessaryComparison = false,
				-- reportAssertAlwaysTrue = false,
				-- reportSelfClsParameterName = false,
				-- reportImplicitStringConcatenation = false,
				-- reportUnsupportedDunderAll = false,
				-- reportUnusedCallResult = false,
				-- reportUnusedCoroutine = false,
				-- reportUninitializedInstanceVariable = true,
			},
			inlayHints = {
				includeInlayEnumMemberValueHints = true,
				includeInlayFunctionLikeReturnTypeHints = true,
				includeInlayFunctionParameterTypeHints = true,
				includeInlayParameterNameHints = true,
				includeInlayParameterNameHintsWhenArgumentMatchesName = true,
				includeInlayPropertyDeclarationTypeHints = true,
				includeInlayVariableTypeHints = true,
			},
		},
	},
}
