github.com:
    user: k1ng93
    git_protocol: https
    users:
        k1ng93:
            oauth_token: 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
        k1ng2193:
    oauth_token: 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
